/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busSystem;

import java.awt.Color;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ELCOT
 */
public class Parent extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Parent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        childID = new javax.swing.JTextField();
        FindJourney = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Details = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,150));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("PARENT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Child ID :");

        childID.setBackground(new java.awt.Color(0, 0, 0));
        childID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        childID.setForeground(new java.awt.Color(255, 255, 255));

        FindJourney.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        FindJourney.setText("Find Journey");
        FindJourney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FindJourney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FindJourneyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FindJourneyMouseExited(evt);
            }
        });
        FindJourney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindJourneyActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        Details.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Details.setText("View Details");
        Details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DetailsMouseExited(evt);
            }
        });
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel3)
                        .addGap(147, 147, 147)
                        .addComponent(childID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(FindJourney)
                        .addGap(103, 103, 103)
                        .addComponent(Details)))
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logout))
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(childID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindJourney)
                    .addComponent(Details))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 700);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus 1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 1042, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindJourneyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindJourneyMouseEntered
        // TODO add your handling code here:
        Color c1 = new Color(51,255,255);
        FindJourney.setBackground(c1);
    }//GEN-LAST:event_FindJourneyMouseEntered

    private void FindJourneyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindJourneyMouseExited
        // TODO add your handling code here:
        Color c1 = new Color(255,255,255);
        FindJourney.setBackground(c1);
    }//GEN-LAST:event_FindJourneyMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        Color c1 = new Color(51,255,255);
        logout.setBackground(c1);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        Color c1 = new Color(255,255,255);
        logout.setBackground(c1);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    String conduct="";
    private void FindJourneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindJourneyActionPerformed
        // TODO add your handling code here:
        String query="SELECT * FROM PASSENGER WHERE USERNAME=?";
        //String query1="SELECT * FROM CONDUCTOR WHERE CID=?";
        String user=childID.getText().trim();
            try {
                PreparedStatement ps=(PreparedStatement)DbConnect.getConnection().prepareStatement(query);
                ps.setString(1, user);

                ResultSet rs=ps.executeQuery();
                
                //PreparedStatement ps1=(PreparedStatement)DbConnect.getConnection().prepareStatement(query1);
                //ps1.setString(1, TicketIssue.conduct);
                
                //ResultSet rs1=ps1.executeQuery();
                if(rs.next()){
                    conduct=rs.getString("conID");
                    JOptionPane.showMessageDialog(null,"Your child, "+rs.getString("Name")+", "+"with us!!\n\n"
                            + "From : "+rs.getString("FromWhere")+"\n"
                            + "To :   "+rs.getString("ToWhere")+"\n"
                            + "Distance :   "+rs.getString("distance")+"\n"
                            + "Price :   Rs."+rs.getString("Price")+"\n"
                            +"\n\nLet your chid to have HAPPY JOURNEY!!    "
                    );
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
    }//GEN-LAST:event_FindJourneyActionPerformed

    private void DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailsMouseEntered
        // TODO add your handling code here:
        Color c1 = new Color(51,255,255);
        Details.setBackground(c1);
    }//GEN-LAST:event_DetailsMouseEntered

    private void DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailsMouseExited
        // TODO add your handling code here:
         Color c1 = new Color(255,255,255);
        Details.setBackground(c1);
    }//GEN-LAST:event_DetailsMouseExited

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        // TODO add your handling code here:
        String query1="SELECT * FROM CONDUCTOR WHERE CID=?";
        //String user=childID.getText().trim();
            try {
                PreparedStatement ps1=(PreparedStatement)DbConnect.getConnection().prepareStatement(query1);
                ps1.setString(1, conduct);
                
                ResultSet rs1=ps1.executeQuery();
                if(rs1.next()){
                    //conduct=rs1.getString("conID");
                    JOptionPane.showMessageDialog(null,"Conductor Details:\nName : "+rs1.getString("CNAME")+"\n"
                            + "Phone : "+rs1.getString("PHONE")+"\n"
                            +"\n\nDon't worry! Your child safe with us!!!    "
                    );
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
    }//GEN-LAST:event_DetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Details;
    private javax.swing.JButton FindJourney;
    private javax.swing.JTextField childID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
