/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busSystem;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.*;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
/**
 *
 * @author ELCOT
 */ 
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        conpass = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        date = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,150));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("REGISTER");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(380, 10, 168, 43);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 500, 220, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 250, 80, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Role :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(140, 80, 80, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone number :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 190, 170, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DOB :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(140, 310, 80, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(140, 380, 130, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 440, 130, 50);

        signup.setBackground(new java.awt.Color(255, 255, 255));
        signup.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        signup.setText("Sign up");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel2.add(signup);
        signup.setBounds(260, 600, 130, 33);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(550, 600, 130, 33);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(140, 130, 80, 50);

        role.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conductor", "Passenger", "Parent", "Admin" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jPanel2.add(role);
        role.setBounds(460, 90, 210, 31);

        conpass.setBackground(new java.awt.Color(0, 0, 0));
        conpass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        conpass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(conpass);
        conpass.setBounds(460, 500, 250, 40);

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(name);
        name.setBounds(460, 140, 250, 40);

        uname.setBackground(new java.awt.Color(0, 0, 0));
        uname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel2.add(uname);
        uname.setBounds(460, 380, 250, 40);

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(email);
        email.setBounds(460, 260, 380, 40);

        phone.setBackground(new java.awt.Color(0, 0, 0));
        phone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(phone);
        phone.setBounds(460, 200, 250, 40);

        pass.setBackground(new java.awt.Color(0, 0, 0));
        pass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pass);
        pass.setBounds(460, 440, 250, 40);

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(date);
        date.setBounds(460, 320, 180, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 700);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus 1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 1042, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        // TODO add your handling code here:
        Color c1 = new Color(51,255,255);
        signup.setBackground(c1);
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        // TODO add your handling code here:
        Color c1 = new Color(255,255,255);
        signup.setBackground(c1);
    }//GEN-LAST:event_signupMouseExited

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        String nam=name.getText().trim();
        String phon=phone.getText().trim();
        String mail=email.getText().trim();
        String dob=null;
        String user=uname.getText().trim();
        String pwd=String.valueOf(pass.getPassword());
        String cpwd=String.valueOf(conpass.getPassword());
        String rol=role.getSelectedItem().toString();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        dob = dateformat.format(date.getDate());
        int age=ageFind(dob);
            
        if(nam.equals(""))
            JOptionPane.showMessageDialog(null,"Please enter your name!");
        else if(phon.equals("") || isValidPhone(phon)!=true){
            JOptionPane.showMessageDialog(null,"Invalid mobile number!");
            phone.setText("");
        }
        else if(mail.equals("") || isValidMail(mail)!=true){
            JOptionPane.showMessageDialog(null,"Invalid email id!");
            email.setText("");
        }
        else if(user.equals("") || user.length()<5){
            JOptionPane.showMessageDialog(null,"Invalid username!"
                    + ""
                    + "\n note: The username shoud be minimum 5 and maximum 20 charcters,\nit can have uppercase, lowercase and only allowed special letter is underscore!!");
            uname.setText("");
        }
        else if(pwd.equals("") || isValidPassword(pwd)!=true){
            JOptionPane.showMessageDialog(null,"Invalid password! \nusername should be minimum 8 characters and maximum 20!");
            pass.setText("");
        }
        else if(!pwd.equals(cpwd)){
            JOptionPane.showMessageDialog(null,"Please retype the CORRECT PASSWORD");
            conpass.setText("");
        }
        else if(dob==null){
            JOptionPane.showMessageDialog(null,"Please choose your date of birth!");
        }
        else{
            if(rol.equals("Passenger")){
                try{
                    String query="INSERT INTO PASSENGER(USERNAME,PASSWORD,NAME,PHONE,AGE,EMAIL) VALUES(?,?,?,?,?,?)";
                    PreparedStatement ps=(PreparedStatement)DbConnect.getConnection().prepareStatement(query);
                    ps.setString(1,user);
                    ps.setString(2,pwd);
                    ps.setString(3,nam);
                    ps.setString(4,phon);
                    ps.setInt(5,age);
                    ps.setString(6,mail);
                    
                    int row=ps.executeUpdate();
                    if(row>0){
                        JOptionPane.showMessageDialog(null,"Hello "+nam+","+"\nWelcome to our family!");
                        this.setVisible(false);
                        new Signin().setVisible(true);
                    }
                }
                catch(SQLIntegrityConstraintViolationException e){
                    JOptionPane.showMessageDialog(null,"Username already exists!","Message",JOptionPane.WARNING_MESSAGE);
                }
                catch(Exception e){
                    System.out.println(e);
                }
            }else if(rol.equals("Conductor")){
                try{
                    String query="INSERT INTO CONDUCTOR VALUES(?,?,?,?)";
                    PreparedStatement ps=(PreparedStatement)DbConnect.getConnection().prepareStatement(query);
                    ps.setString(1,user);
                    ps.setString(2,nam);
                    ps.setString(3,phon);
                    ps.setString(4,pwd);
                    
                    int row=ps.executeUpdate();
                    if(row>0){
                        JOptionPane.showMessageDialog(null,"Hello "+nam+","+"\nWelcome to our family!");
                        this.setVisible(false);
                        new Signin().setVisible(true);
                    }
                }
                catch(SQLIntegrityConstraintViolationException e){
                    JOptionPane.showMessageDialog(null,"Username already exists!","Message",JOptionPane.WARNING_MESSAGE);
                }
                catch(Exception e){
                    System.out.println(e);
                }
            }else if(rol.equals("Parent")){
                try{
                    String query="INSERT INTO PARENT (CHID,NAME,PHONE,PASSWORD,EMAIL) VALUES(?,?,?,?,?)";
                    PreparedStatement ps=(PreparedStatement)DbConnect.getConnection().prepareStatement(query);
                    ps.setString(1,user);
                    ps.setString(2,nam);
                    ps.setString(3,phon);
                    ps.setString(4,pwd);
                    ps.setString(5, mail);
                    
                    int row=ps.executeUpdate();
                    if(row>0){
                        JOptionPane.showMessageDialog(null,"Hello "+nam+","+"\nWelcome to our family!");
                        this.setVisible(false);
                        new Login().setVisible(true);
                        EmailSend.sendEmail(mail,nam,"Register","","");
                    }
                    
                    String query1="INSERT INTO PASSENGER (USERNAME,PASSWORD,NAME,PHONE,AGE,EMAIL) VALUES(?,?,?,?,?,?)";
                    ps=(PreparedStatement)DbConnect.getConnection().prepareStatement(query1);
                    ps.setString(1,user);
                    ps.setString(2,pwd);
                    ps.setString(3,nam);
                    ps.setString(4,phon);
                    ps.setInt(5,age);
                    ps.setString(6,mail);
                    
                    row=ps.executeUpdate();
                }
                catch(SQLIntegrityConstraintViolationException e){
                    JOptionPane.showMessageDialog(null,"Username already exists!","Message",JOptionPane.WARNING_MESSAGE);
                }
                catch(Exception e){
                    System.out.println(e);
                }
            }else{
                try{
                    String query="INSERT INTO ADMIN VALUES(?,?)";
                    PreparedStatement ps=(PreparedStatement)DbConnect.getConnection().prepareStatement(query);
                    ps.setString(1,user);
                    ps.setString(2,pwd);
                    
                    int row=ps.executeUpdate();
                    if(row>0){
                        JOptionPane.showMessageDialog(null,"Hello "+nam+","+"\nWelcome to our family!");
                        this.setVisible(false);
                        new Signin().setVisible(true);
                    }
                }
                catch(SQLIntegrityConstraintViolationException e){
                    JOptionPane.showMessageDialog(null,"Username already exists!","Message",JOptionPane.WARNING_MESSAGE);
                }
                catch(Exception e){
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_signupActionPerformed
    
    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        Color c1 = new Color(51,255,255);
        back.setBackground(c1);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        Color c1 = new Color(255,255,255);
        back.setBackground(c1);
    }//GEN-LAST:event_backMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Signin().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    public static boolean isValidPhone(String phone){
        String phoneFormat="[6-9]\\d{9}$";
        Pattern p=Pattern.compile(phoneFormat,Pattern.CASE_INSENSITIVE);
        Matcher m=p.matcher(phone);
        return m.find();
    }
    
    public static boolean isValidMail(String mail){
        String mailFormat="^[A-Z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,6}$";
        Pattern p=Pattern.compile(mailFormat,Pattern.CASE_INSENSITIVE);
        Matcher m=p.matcher(mail);
        return m.find();
    }
    
    public static boolean isValidPassword(String password) {
        if (password.length() < 8 && password.length()>20) {
            return false;
        }
        boolean hasUppercase = false;
        boolean hasLowercase = false;
        boolean hasDigit = false;
        boolean hasSpecialChar = false;
        String specialChars = "~`!@#$%^&*()-_=+\\|[{]};:'\",<.>/?";

        for (char c : password.toCharArray()) {
            if (Character.isUpperCase(c)) {
                hasUppercase = true;
            } else if (Character.isLowerCase(c)) {
                hasLowercase = true;
            } else if (Character.isDigit(c)) {
                hasDigit = true;
            } else if (specialChars.contains(Character.toString(c))) {
                hasSpecialChar = true;
            }
        }
        return hasUppercase && hasLowercase && hasDigit && hasSpecialChar;
    }

    public static boolean isValidUsername(String username) {
        String regex = "^[a-zA-Z0-9_]+$";
        if (username.length() < 5 || username.length() > 25) { 
            return false;
        }
        if (!username.matches(regex)) {
            return false;
        }
        return true;
    }
    
    public static int ageFind(String date){
        LocalDate dob = LocalDate.parse(date);
        LocalDate currentDate = LocalDate.now();
        Period age = Period.between(dob, currentDate);
        return age.getYears();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPasswordField conpass;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton signup;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
